version: '2'

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local

services:
  db:
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/backups:/db/backups
    environment:
      POSTGRES_PASSWORD: P4Ssw0rD!

  app: &app
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    stdin_open: true
    tty: true
    links:
      - db

  web:
    <<: *app
    command: rails server -b 0.0.0.0 -p 3000 -P /tmp/rails.pid
    ports:
      - 3000:3000
    environment:
      PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/graveler_dev"
      RAILS_ENV: development
      RACK_ENV: development
    env_file:
      - dev.env
    links:
      - webpack

  test:
    <<: *app
    environment:
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/graveler_dev"
      RAILS_ENV: test
      RACK_ENV: test
    env_file:
      - test.env

  webpack:
    <<: *app
    command: webpack-dev-server --host 0.0.0.0 --inline true --hot false
    ports:
      - 8080:8080
    environment:
      PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      RAILS_ENV: development
      RACK_ENV: development
    env_file:
      - dev.env